version: '3.10'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    restart: always

  grpc:
    build: .
    command: python grpc_server.py
    restart: always
    ports:
      - "50051:50051"
