# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/grpc_services/restaurant_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*src/grpc_services/restaurant_service.proto\x12\nrestaurant\"\'\n\x17\x43reateRestaurantRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"%\n\x12RestaurantResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2l\n\x11RestaurantService\x12W\n\x10\x43reateRestaurant\x12#.restaurant.CreateRestaurantRequest\x1a\x1e.restaurant.RestaurantResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.grpc_services.restaurant_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATERESTAURANTREQUEST']._serialized_start=58
  _globals['_CREATERESTAURANTREQUEST']._serialized_end=97
  _globals['_RESTAURANTRESPONSE']._serialized_start=99
  _globals['_RESTAURANTRESPONSE']._serialized_end=136
  _globals['_RESTAURANTSERVICE']._serialized_start=138
  _globals['_RESTAURANTSERVICE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
