# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.grpc_services import restaurant_service_pb2 as src_dot_grpc__services_dot_restaurant__service__pb2


class RestaurantServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateRestaurant = channel.unary_unary(
                '/restaurant.RestaurantService/CreateRestaurant',
                request_serializer=src_dot_grpc__services_dot_restaurant__service__pb2.CreateRestaurantRequest.SerializeToString,
                response_deserializer=src_dot_grpc__services_dot_restaurant__service__pb2.RestaurantResponse.FromString,
                )


class RestaurantServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateRestaurant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RestaurantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateRestaurant': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRestaurant,
                    request_deserializer=src_dot_grpc__services_dot_restaurant__service__pb2.CreateRestaurantRequest.FromString,
                    response_serializer=src_dot_grpc__services_dot_restaurant__service__pb2.RestaurantResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'restaurant.RestaurantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RestaurantService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateRestaurant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/restaurant.RestaurantService/CreateRestaurant',
            src_dot_grpc__services_dot_restaurant__service__pb2.CreateRestaurantRequest.SerializeToString,
            src_dot_grpc__services_dot_restaurant__service__pb2.RestaurantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
